### ISSUE TITLE
Project feedback 26/3 (Ciaran & Andrei)

### ISSUE THREAD

**Issue by revforev** [fac30/ali-nas-travel-blog#31]
README
[The readme file is very good. 
It could be simplified just a little bit further,
The paragraphs with 2-3 lines can feel a bit like a block of text,
So maybe would look better spread between more lines]

User stories
[The project meets user stories.]

Learning outcomes
[It does demonstrate the learning outcomes very well.]

UI bugs
[We were not able to find any bugs]

File structure
[The file structure makes sense.
We notice you used ejs which seems like good practice.
The images could be optimised as some of them are quite large
(over 1.5mb) which can affect loading time.
A good tool for optimizing images quick is RIOT: 
https://riot-optimizer.com/
]

Flow of control
[Yes.]

Naming
[The naming is mostly good. 
There were bits which were hard to understand but not due to naming.]

Readability
[We understood bits of the code, but not everything.
There were no comments in the code which made it hard to read.
While a code with no comments might work perfectly internally, commenting
out things (such as what functions do) might be super helpful for someone who 
does not know the code. But in rest the code is clean and readable.]

**Comment by nascho** [comment]
Thanks
